name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: "Setup Cipherguard"
        run: |
            git clone https://github.com/khulnasoft/cipherguard_docker.git ../cipherguard_docker
            cd ../cipherguard_docker
            docker-compose -f docker-compose/docker-compose-ce.yaml up -d
            docker ps -a
      - name: "Test"
        run: |
            docker exec docker-compose_cipherguard_1 sh -c '/usr/bin/wait-for.sh -t 30 localhost:443'
            output=$(docker exec docker-compose_cipherguard_1 sh -c 'su -m -c "/usr/share/php/cipherguard/bin/cake \
              cipherguard register_user \
              -u your@email.com \
              -f yourname \
              -l surname \
              -r admin" -s /bin/sh www-data')
            export REG_URL=$(echo ${output##* your mailbox or here: } | tr -d '\n')
            echo "Register with $REG_URL"
            go test -v ./...
